g2t_ops v2.1.0
eastgenomics/generate_g2t pull request #12
Opened 2023-11-15 15:33 UTC by kjwinfield

Update g2t_ops script to work with a RefSeq MANE b38 gff (from: https://ftp.ncbi.nlm.nih.gov/refseq/MANE/MANE_human/), while still working with an Ensembl MANE Select b37 csv (from: http://tark.ensembl.org/web/mane_GRCh37_list/)

Changes made:
- Add new argument `--mane_gff` to pass a RefSeq MANE gff for b38 to be passed to the script
- Make argument --mane_select optional, so the script can be run with both an Ensembl MANE b37 csv and a RefSeq MANE gff
- Add function `parse_mane_gff` to create sqlite db from gff
- Add function `get_mane_transcripts_from_b38_gff` to extract MANE data from sqlite db from gff
-  Change function `write_sql_queries` so it only takes lists, rather than a mixture of lists and strings
- Allow multiple clinical transcripts for one gene, to allow a gene to have a MANE Select and a MANE Plus Clinical labelled as such.
- Add new requirements to requirements.txt
- Edit readme, addressing Git Issues #11 and #10

2023-11-15 15:33 UTC, pep8speaks commented
Hello @kjwinfield! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`g2t_ops/transcript_assigner.py`](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py):

> [Line 110:1](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L110): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 224:80](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L224): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 253:13](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L253): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 256:80](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L256): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)
> [Line 312:80](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L312): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)

2023-11-15 15:54 UTC, Yu-jinKim requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/12)* status: all files reviewed, 10 unresolved discussions (waiting on @kjwinfield)

___
*[`g2t_ops/transcript_assigner.py` line 106 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjId0V74Uhu95BqEvKO:-NjId0V74Uhu95BqEvKP:b-xie2gw) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L106)):*
> ```Python
>         ]
> 
>         if hgnc_list != []:
> ```

you can simplify by writing `if hgnc_list:`
___
*[`g2t_ops/transcript_assigner.py` line 107 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIcg1V1UvW641ln-3a:-NjIcg1V1UvW641ln-3b:b-4bzmox) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L107)):*
> ```Python
> 
>         if hgnc_list != []:
>             hgnc_id = hgnc_list[0].split(":", 1)[-1]
> ```

is the 1 in the split necessary?
does this element have more than one outcome after a normal split?
___
*[`g2t_ops/transcript_assigner.py` line 202 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIdSIX3I1Jd_MjHX-V:-NjIdSIX3I1Jd_MjHX-W:bvsjlyj) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L202)):*
> ```Python
> 
>             if gene in mane_select_data:
>                 # If mane_select_data is a dictionary, it was made by the
> ```

`mane_select_data[gene]` rather than just `mane_select_data`
___
*[`g2t_ops/transcript_assigner.py` line 208 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIe-wf3gKgwfGswbm2:-NjIe-wf3gKgwfGswbm3:b-9mshdx) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L208)):*
> ```Python
>                     # Convert keys into list to iterate over
>                     query_mane_transcripts = mane_transcripts.keys()
>                     query_mane_transcripts = list(query_mane_transcripts)
> ```

you can simplify by doing `query_mane_transcripts = list(mane_transcripts.keys())`



_Code quote:_
```Python
                    query_mane_transcripts = mane_transcripts.keys()
                    query_mane_transcripts = list(query_mane_transcripts)
```
___
*[`g2t_ops/transcript_assigner.py` line 244 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIfEyHBzt2-cyQNdKj:-NjIfEyHBzt2-cyQNdKk:b-4g7oub) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L244)):*
> ```Python
> 
>                 if tx_base == hgmd_base:
>                     if "clinical_transcript" in data[gene]:
> ```

this check might be better placed before looking for a HGMD transcript that way you don't waste time looking through HGMD when you already have a clinical transcript
___
*[`g2t_ops/transcript_assigner.py` line 256 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIfpFC59kHjW5dXa4Z:-NjIfpFD-3vY6zSLo9pq:b-skkyfk) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L256)):*
> ```Python
>                 # Check the query transcript is not already listed. If not,
>                 # add it as a non-clinical transcript
>                 if any(tx in sublist for sublist in data[gene]["clinical_transcript"]) is False:
> ```

can the `else` case for this `if` happen?
___
*[`g2t_ops/__pycache__/__init__.cpython-38.pyc` line 0 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIg2Xl03j4WBGgR8Rv:-NjIg2Xl03j4WBGgR8Rw:bg3bhrg) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/__pycache__/__init__.cpython-38.pyc#L0)):*
can the .pyc be removed?
___
*[`g2t_ops/__pycache__/convert_symbols.cpython-38.pyc` line 0 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIg6U23iXyZ1UpmDM2:-NjIg6U23iXyZ1UpmDM3:bg3bhrg) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/__pycache__/convert_symbols.cpython-38.pyc#L0)):*
can the .pyc be removed?
___
*[`g2t_ops/__pycache__/transcript_assigner.cpython-38.pyc` line 0 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIg6uD15paMbo6LvIX:-NjIg6uD15paMbo6LvIY:bg3bhrg) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/__pycache__/transcript_assigner.cpython-38.pyc#L0)):*
can the .pyc be removed?
___
*[`g2t_ops/__pycache__/utils.cpython-38.pyc` line 0 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIg7QqCBjJH0qFlHv4:-NjIg7QqCBjJH0qFlHv5:bg3bhrg) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/__pycache__/utils.cpython-38.pyc#L0)):*
can the .pyc be removed?


<!-- Sent from Reviewable.io -->

2023-11-17 16:41 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/12)* status: 2 of 8 files reviewed, 10 unresolved discussions (waiting on @Yu-jinKim)

___
*[`g2t_ops/transcript_assigner.py` line 106 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjId0V74Uhu95BqEvKO:-NjNfmxM8uKu3MnJJBNh:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L106)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

you can simplify by writing `if hgnc_list:`
</blockquote></details>

Done.
___
*[`g2t_ops/transcript_assigner.py` line 107 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIcg1V1UvW641ln-3a:-NjImwT7BLc3oTgM4MT_:b-fata5j) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L107)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

is the 1 in the split necessary?
does this element have more than one outcome after a normal split?
</blockquote></details>

The HGNC is in the gff as `HGNC:HGNC:14825` so this split just gets rid of the first HGNC, not the second
___
*[`g2t_ops/transcript_assigner.py` line 202 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIdSIX3I1Jd_MjHX-V:-NjT3y3zE8YsqHz25e36:bfaj2mx) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L202)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

`mane_select_data[gene]` rather than just `mane_select_data`
</blockquote></details>

Deleted section
___
*[`g2t_ops/transcript_assigner.py` line 208 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIe-wf3gKgwfGswbm2:-NjNerNIB9i2IG6oNPK-:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L208)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

you can simplify by doing `query_mane_transcripts = list(mane_transcripts.keys())`
</blockquote></details>

Done.
___
*[`g2t_ops/transcript_assigner.py` line 244 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIfEyHBzt2-cyQNdKj:-NjMn9h6Dn0C1guIQJ2z:bfk0sle) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L244)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

this check might be better placed before looking for a HGMD transcript that way you don't waste time looking through HGMD when you already have a clinical transcript
</blockquote></details>

this section determines whether to label a matched HGMD transcript as "HGMD" or leave it as MANE, in both instances it needs to have previously filtered based on whether the transcript matches
___
*[`g2t_ops/transcript_assigner.py` line 256 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIfpFC59kHjW5dXa4Z:-NjMnFPx9XC66ZLfcSSt:b4juabo) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/transcript_assigner.py#L256)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can the `else` case for this `if` happen?
</blockquote></details>

yes, the same transcript can come through twice. Without this, transcripts added as MANE Select  are added again as 'no_clinical_transcript'
___
*[`g2t_ops/__pycache__/__init__.cpython-38.pyc` line  at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIg2Xl03j4WBGgR8Rv:-NjNetiO2IPMQegMJ3vl:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/__pycache__/__init__.cpython-38.pyc#L)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can the .pyc be removed?
</blockquote></details>

Done.
___
*[`g2t_ops/__pycache__/convert_symbols.cpython-38.pyc` line  at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIg6U23iXyZ1UpmDM2:-NjNeu9477DWmtP5RdOU:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/__pycache__/convert_symbols.cpython-38.pyc#L)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can the .pyc be removed?
</blockquote></details>

Done.
___
*[`g2t_ops/__pycache__/transcript_assigner.cpython-38.pyc` line  at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIg6uD15paMbo6LvIX:-NjNeuPf9AKA2T5HxS9V:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/__pycache__/transcript_assigner.cpython-38.pyc#L)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can the .pyc be removed?
</blockquote></details>

Done.
___
*[`g2t_ops/__pycache__/utils.cpython-38.pyc` line  at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/12#-NjIg7QqCBjJH0qFlHv4:-NjNeukzBpIFPyf2z3G4:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/c74929eb58718e39c834f9b027100e30e6e049ce/g2t_ops/__pycache__/utils.cpython-38.pyc#L)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can the .pyc be removed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-20 09:48 UTC, Yu-jinKim approved these changes
> Reviewed 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kjwinfield)



<!-- Sent from Reviewable.io -->

2023-11-20 09:48 UTC, merged